[package]
name = "caidex-credentials"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["linux-secret-service"]
linux-secret-service = ["dep:keyring"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zeroize = "=1.9.0"

[target.'cfg(unix)'.dependencies]
libc = "=0.2.190"

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "=3.6.3", optional = true, default-features = false, features = ["sync-secret-service", "crypto-rust", "vendored"] }

[target.'cfg(windows)'.dependencies]
keyring = { version = "=3.6.3", default-features = false, features = ["windows-native"] }
